// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYHis1xBBrOHQBGJf4hgu8vlTupZVfxI0',
    appId: '1:773834747644:web:882d7e6d6b01a939c5b179',
    messagingSenderId: '773834747644',
    projectId: 'qrcode-31ef2',
    authDomain: 'qrcode-31ef2.firebaseapp.com',
    storageBucket: 'qrcode-31ef2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB43O_ZLSoliFT7qUmWU9X5OSItuNUckyk',
    appId: '1:598002815780:android:2e9b91338116f369f019b1',
    messagingSenderId: '598002815780',
    projectId: 'myqr-653bb',
    storageBucket: 'myqr-653bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHbqPML4bfJLtGW5iGZdjBCOH2-dwLVSM',
    appId: '1:773834747644:ios:4490ea7ca1e97f4dc5b179',
    messagingSenderId: '773834747644',
    projectId: 'qrcode-31ef2',
    storageBucket: 'qrcode-31ef2.firebasestorage.app',
    iosBundleId: 'com.chels.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHbqPML4bfJLtGW5iGZdjBCOH2-dwLVSM',
    appId: '1:773834747644:ios:4490ea7ca1e97f4dc5b179',
    messagingSenderId: '773834747644',
    projectId: 'qrcode-31ef2',
    storageBucket: 'qrcode-31ef2.firebasestorage.app',
    iosBundleId: 'com.chels.qrCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYHis1xBBrOHQBGJf4hgu8vlTupZVfxI0',
    appId: '1:773834747644:web:5a5b69ac95e7f062c5b179',
    messagingSenderId: '773834747644',
    projectId: 'qrcode-31ef2',
    authDomain: 'qrcode-31ef2.firebaseapp.com',
    storageBucket: 'qrcode-31ef2.firebasestorage.app',
  );
}